import { Outfit } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/shared/Nav/Nav";
import Footer from "@/pages/home/Footer/Footer";

const outfit = Outfit({
  subsets: ["latin"],
  display: "fallback",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${outfit.className} container mx-auto`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
