import { Outfit } from "next/font/google";
import "./globals.css";
import { Nav } from "@/components/shared/Nav/Nav";
import Footer from "@/pages/home/Footer/Footer";

const outfit = Outfit({
  subsets: ["latin"],
  display: "fallback",
});

export const metadata = {
  title: "BackBenchers IT House",
  description: "Generated by BBITH Front-End Team",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} max-w-7xl mx-auto lg:px-0 px-5 gradient-bg`}
      >
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
